### ISSUE TITLE
Cannot delete first line with `dd`

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [LightTable/Vim#53]
I'm getting the following error, when I have a single-line document, and I try to delete to the start of the line with `dd`:

```
Error: There is no line -1 in the document.
    at getLine (/opt/homebrew-cask/Caskroom/lighttable/0.7.2/LightTable/LightTable.app/Contents/Resources/app.nw/core/node_modules/codemirror/codemirror.js:6721:39)
    at cursorCoords (/opt/homebrew-cask/Caskroom/lighttable/0.7.2/LightTable/LightTable.app/Contents/Resources/app.nw/core/node_modules/codemirror/codemirror.js:1789:26)
    at drawSelectionCursor (/opt/homebrew-cask/Caskroom/lighttable/0.7.2/LightTable/LightTable.app/Contents/Resources/app.nw/core/node_modules/codemirror/codemirror.js:1299:15)
    at drawSelection (/opt/homebrew-cask/Caskroom/lighttable/0.7.2/LightTable/LightTable.app/Contents/Resources/app.nw/core/node_modules/codemirror/codemirror.js:1266:9)
    at endOperation_R2 (/opt/homebrew-cask/Caskroom/lighttable/0.7.2/LightTable/LightTable.app/Contents/Resources/app.nw/core/node_modules/codemirror/codemirror.js:2053:30)
    at endOperations (/opt/homebrew-cask/Caskroom/lighttable/0.7.2/LightTable/LightTable.app/Contents/Resources/app.nw/core/node_modules/codemirror/codemirror.js:2014:7)
    at endOperation (/opt/homebrew-cask/Caskroom/lighttable/0.7.2/LightTable/LightTable.app/Contents/Resources/app.nw/core/node_modules/codemirror/codemirror.js:2001:7)
    at eval (/opt/homebrew-cask/Caskroom/lighttable/0.7.2/LightTable/LightTable.app/Contents/Resources/app.nw/core/node_modules/codemirror/codemirror.js:2147:17)
    at CodeMirror.setOption (/opt/homebrew-cask/Caskroom/lighttable/0.7.2/LightTable/LightTable.app/Contents/Resources/app.nw/core/node_modules/codemirror/codemirror.js:4020:48)
    at lt.objs.editor.set_mode (file:///opt/homebrew-cask/Caskroom/lighttable/0.7.2/LightTable/LightTable.app/Contents/Resources/app.nw/core/node_modules/lighttable/bootstrap.js:23804:43)
```

**Comment by cldwalker** [comment]
This has been fixed [upstream in 4.7.0](https://github.com/codemirror/CodeMirror/commit/8288002f672064cafa3219396dffd83900ad6a7c). Once we can upgrade in #45, this should be fixed
